import { initTheme } from "./behaviors/theme.js";
import { initNavigation } from "./behaviors/navigation.js";
import { initReveals } from "./behaviors/reveal.js";
import { initSectionParallax } from "./behaviors/section-parallax.js";
import { initCaseDialogs } from "./behaviors/case-dialogs.js";
initTheme();
initNavigation();
initReveals();
initSectionParallax();
initCaseDialogs();
