import { initTheme } from "./behaviors/theme.js";
import { initNavigation } from "./behaviors/navigation.js";
import { initReveals } from "./behaviors/reveal.js";
import { initHeroParallax } from "./behaviors/hero-parallax.js";
import { initCaseDialogs } from "./behaviors/case-dialogs.js";
initTheme();
initNavigation();
initReveals();
initHeroParallax();
initCaseDialogs();
